### ISSUE TITLE
Remove .platform stuff

### ISSUE THREAD

**Issue by tombasche** [tombasche/BookChook#19]
This was guff I added to test `platform.sh` which turned out to be sub-par and actually cost lots of money

**Comment by cybergaala** [comment]
Can you give me more information?

**Comment by tombasche** [comment]
Just delete the .platform folder :)

**Comment by tombasche** [comment]
oh! and also the `.platform.app.yaml` file

**Comment by cybergaala** [comment]
Sure :D
